name: Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'               # Triggert bei Tags wie v1.2.3
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install package in editable mode + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-django

      - name: Run pytest
        run: python3 -m pytest --maxfail=1 --disable-warnings -q

  release:
    name: 🚀 Release
    needs: test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      id-token: write       # für Actions @v4 nötig
      contents: write       # um Commits, Tags & Releases zu pushen

    steps:
      # 1) Vollständiges Repo auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2) Python bereitstellen
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 3) Semantic Release ausführen (Version-Bump, Tag, GitHub-Release, PyPI-Upload)
      - id: semantic_release
        name: Semantic Version Release
        uses: python-semantic-release/python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: "false"          # → (--skip-build) :contentReference[oaicite:0]{index=0}
          git_committer_name:  "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      - name: Build & Publish to PyPI
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      # 4) (Optional) Artefakte in GitHub-Release hochladen
      - name: Publish to GitHub Release Assets
        if: steps.semantic_release.outputs.released == 'true'
        uses: python-semantic-release/publish-action@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semantic_release.outputs.tag }}