name: Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'               # Veröffentlichungen bei Tags wie v0.1.0
  pull_request:
    branches:
      - main

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install package in editable mode + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .        # installiert general_manager
          pip install pytest pytest-django

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  publish:
    name: 🚀 Publish to PyPI
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

